# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
#  - build
  - test
#  - deploy

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
      - .cache/pip
      - venv
      - .pub-cache/global_packages


# TEST

frontend-test:
    image: cirrusci/flutter:stable
    stage: test
    script:
        - cd frontend
        - flutter pub get
        - flutter test --coverage

frontend-analyze:
    image: cirrusci/flutter:stable
    stage: test
    script:
        - cd frontend
        - flutter pub get
        - flutter analyze

backend-test:
    image: python:3.9
    stage: test
    script:
        - cd backend
        - make install
        - make test

backend-lint:
    image: python:3.9
    stage: test
    script:
        - cd backend
        - make install
        - make precommit


# DEPLOY

#deploy-job:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
