# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
#  - build
  - test
#  - deploy

default:
    image: python:3.9
#    before_script:
#        - pip3 install -r requirements-dev.txt

#build:
#  stage: build
#  script:
#    - python3 --version
#    - make install

test:
    stage: test
    script:
        - make install
        - make test

lint:
    stage: test
    script:
        - make install
        - make precommit

#deploy-job:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
