version: '3.8'

volumes:
  frontend-build:

services:
#  database:
#    image: postgres:latest
#    container_name: database
#    restart: unless-stopped
#    volumes:
#      - /var/lib/postgresql
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      args:
        CORE_PUBLIC_FRONTEND_URL: ${CORE_PUBLIC_FRONTEND_URL}
        CORE_PUBLIC_API_URL: ${CORE_PUBLIC_API_URL}
#    volumes:
#      - ./backend:/usr/src/backend
#    depends_on:
#      - database
#    links:
#      - database
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        API_URL: /api
    volumes:
      - frontend-build:/usr/src/frontend/build

  webserver:
    container_name: webserver
    restart: unless-stopped
    build: ./compose/webserver
    volumes:
      - frontend-build:/usr/src/frontend/build
    depends_on:
      - backend
      - frontend
    links:
      - backend
    ports:
      - "80:80"
