[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_third_party = [
    "flask",
]



[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
    \.git
  | \.mypy_cache
  | build
  | dist
  | ^/venv
)
'''



[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = [
    "blinker",
]
ignore_missing_imports = true
